server:
  port: 8080
  servlet:
    path: /

spring:
    jmx:
      enabled: false
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://39.107.110.164:3306/ordersystem
        username: root
        password: MyNewPass4!
        type: com.alibaba.druid.pool.DruidDataSource
        connectionProperties: druid.stat.mergeSql=true

    #hibernate配置
    jpa:
      database: mysql
      show-sql: false
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

    http:
      encoding:
        force: true
        enabled: true
        charset: utf-8

#日志配置
logging:
  file: ijpay.log
  level: debug